version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      capacitor:
        patterns:
          - "@capacitor/*"
      ionic:
        patterns:
          - "@ionic/*"
      semantic-release:
        patterns:
          - "*semantic-release*"

  - package-ecosystem: "npm"
    directory: "/example"
    target-branch: "dev"
    schedule:
      interval: "weekly"
    groups:
      capacitor:
        patterns:
          - "@capacitor/*"

  - package-ecosystem: "gradle"
    directory: "/android"
    target-branch: "dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    target-branch: "dev"
    schedule:
      interval: "weekly"
